### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by kadyb** [USDAForestService/gdalraster#25] opened 2023-05-30 10:13 UTC
Have you tried doing any benchmarks? I think it would be very useful to compare how the low level `{gdalraster}` compares to the high level `{terra}` and `{stars}`, and the old `{rgdal}`. See if there are any differences in performance or it doesn't matter.

**Comment by kadyb** [comment] 2023-05-30 19:34
Here I have a simple comparison with data loading. In general, there are no big differences. We can exclude `{terra}` from this comparison, because data is not actually represented as R object. Later I will prepare more interesting example with multibands.

<details>
<summary>Comparison</summary>
  
```r
library("rgdal")
library("raster")
library("stars")
library("terra")
library("gdalraster")
options(timeout = 600)

url = "https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_39_02.zip"
dir.create("dem")
download.file(url, "dem/srtm.zip")
unzip("dem/srtm.zip", exdir = "dem") # ~70 MB tif int16
f = "dem/srtm_39_02.tif"

gdalraster_read = function(f) {
  ds = new(GDALRaster, f, read_only = TRUE)
  dm = c(ds$getRasterXSize(), ds$getRasterYSize())
  r = ds$read(1, 0, 0, dm[1], dm[2], dm[1], dm[2])
  dim(r) = dm
  ds$close()
  return(r)
}

rgdal_read = function(f) {
  ds = new("GDALReadOnlyDataset", f)
  r = getRasterData(ds, 1)
  GDAL.close(ds)
  return(r)
}

t = bench::mark(
  check = FALSE, iterations = 10,
  raster = readAll(raster(f)),
  terra = set.values(rast(f)),
  stars = read_stars(f, proxy = FALSE),
  gdalraster = gdalraster_read(f),
  rgdal = rgdal_read(f)
)
t[, 1:5]
#>   expression      min   median `itr/sec` mem_alloc
#> 1 raster        595ms    787ms      1.29   846.1MB
#> 2 terra         299ms    300ms      3.24    3.52KB
#> 3 stars         315ms    331ms      2.86  275.17MB
#> 4 gdalraster    299ms    303ms      3.18  274.66MB
#> 5 rgdal         358ms    376ms      2.58  274.88MB
```

</details>

**Comment by ctoney** [comment] 2023-05-31 02:18
This is interesting. Thank you for providing it. Is the memory allocation what you would expect for {gdalraster} compared with {stars} and {rgdal}, given the buffer of type double that we were previously discussing?

Otherwise, I've been thinking about your question and intend to reply more soon. The short answer is that I use a few "benchmark" tests (not bench::mark) but I probably won't document in a formal way for posting. I'll at least describe informally some of the tests that I track. Those use large raster datasets where concern is with scaling certain types of processing or analysis.  That is the type of use the code needs to support internally, and with user facing code in some cases (some uses of package {FIESTA} via {FIESTAutils}).  That might help explain some of the intent with {gdalraster} which I was expecting could be useful in a narrow niche but not an alternative to packages like {stars} and {terra} for most. That is not a comment on the benchmarks, those are of interest regardless and I'm curious how those relate to my results. Anyway, sorry for the delay. I'll add more soon.

**Comment by ctoney** [comment] 2023-05-31 05:07
In the tests above, gdalraster_read() and rgdal_read() do exactly the same thing: create an object in R, pass filename to GDAL open() method, call read() on the dataset one time, close() the GDAL dataset for cleanup and dereferencing. Same with {stars} except it does not create an object in R, otherwise the same things happen in the C++ code (open, read, close). For a raster that small, the small differences in timings may relate more to overhead in object creation / function calls than the actual read performance which should be similar anyway. {gdalraster} creates an instance of a C++ class, so overhead relates to Rccp exposed class and method calls. I believe {rgdal} creates an S4 object (GDALReadOnlyDataset) which is more on the R side but the C++ code for {rgdal} probably has little additional overhead like that. {stars} does not have object creation in R but there is still function call overhead. These sources of overhead are each a little different but not especially interesting in that case.

But suppose we want to process a large raster, say 155000 x 100000. So we do it row by row which scales up well (and some algorithms are inherently row oriented). So read a row, do some calculation or processing with each pixel and possibly write a row of output, then do the next row. {rgdal} and {gdalraster} each create the dataset object once. That calls GDAL open() method passing in a filename and obtaining a pointer to the opened dataset. The object is then used repeatedly to call read() on each row but there is no more calling open(). When done, the dataset is closed once for cleanup and dereferencing. It is different with {stars}. Each call to read_stars() in turn (in the underlying C++ code) calls GDAL open() passing in a filename, calls read(), then calls GDAL close() on the dataset, repeatedly for each row. If the processing also includes writing an output row, read_stars() does this for the output raster as well, in which case close() includes flushing of pending writes.

I assume that the overhead for GDAL open and close methods is small (considering just the C++ calls in isolation). But I don't know exactly how small. Is it negligible? I'm curious if you have thoughts on this or have looked at anything like that with benchmark tests.

**Comment by kadyb** [comment] 2023-05-31 10:11
Thank you for your detailed answer and sorry for not addressing all the points but I don't know C++ and deep internals.

> Is the memory allocation what you would expect for {gdalraster} compared with {stars} and {rgdal}, given the buffer of type double that we were previously discussing?

I think so. If you implement loading the data as integer type, the size should be reduced by half and maybe it will work a little faster (but I'm just guessing).

> The short answer is that I use a few "benchmark" tests (not bench::mark) but I probably won't document in a formal way for posting.

Maybe it would be good idea to create a vignette with some conclusions about performance or "benchmark" folder with R scripts in the GitHub repository so users can check it for themselves?

> That might help explain some of the intent with {gdalraster} which I was expecting could be useful in a narrow niche but not an alternative to packages like {stars} and {terra} for most.

I am fully aware of this. Generally, why I brought this topic up is that I'm interested in whether using a low-level API can bring any great performance gains. Then some of the performance-critical analysis could be moved to `{gdalraster}`, but the question is are the potential performance gains worth it?

-------

Regarding your second message, I can't say much, because I don't have such knowledge in this topic. Nevertheless, maybe @edzer could comment if we brought up the topic of `{stars}`.

**Comment by kadyb** [comment] 2023-05-31 13:45
This example will be better because it is based on a multiband raster. You have to download the data manually from [this link](https://drive.google.com/uc?id=1lzglfQJqlQh9OWT_-czc5L0hQ1AhoR8M&export=download) (Landsat 8 scene). Here we can see that `{stars}` is a bit faster than `{gdalraster}`, but `{gdalraster}` is faster than `{raster}`, and `{rgdal}` in particular.

<details>
<summary>Comparison</summary>

```r
library("rgdal")
library("raster")
library("stars")
library("terra")
library("gdalraster")
terraOptions(memfrac = 0.9)
rasterOptions(memfrac = 0.9)

## download data manually from below URL (851 MB)
# https://drive.google.com/open?id=1lzglfQJqlQh9OWT_-czc5L0hQ1AhoR8M

unzip("LC08_L1TP_190024_20200418_20200822_02_T1.zip")
f = list.files("LC08_L1TP_190024_20200418_20200822_02_T1", full.names = TRUE)
f = f[4:7] # use only 4 bands
vrt = "vrt.vrt"
terra::vrt(f, vrt, options = "-separate")

gdalraster_read = function(f) {
  ds = new(GDALRaster, f, read_only = TRUE)
  dm = c(ds$getRasterXSize(), ds$getRasterYSize())
  bands = ds$getRasterCount()
  ls = vector("list", bands)
  for (i in seq_len(bands)) {
    ls[[i]] = ds$read(i, 0, 0, dm[1], dm[2], dm[1], dm[2])
  }
  r = array(unlist(ls), dim = c(dm, bands))
  ds$close()
  return(r)
}

rgdal_read = function(f) {
  ds = new("GDALReadOnlyDataset", f)
  bands = dim(ds)[3]
  ls = vector("list", bands)
  for (i in seq_len(bands)) {
    ls[[i]] = getRasterData(ds, i)
  }
  r = array(unlist(ls), dim = c(dim(ds)[2], dim(ds)[1], bands))
  GDAL.close(ds)
  return(r)
}

t = bench::mark(
  check = FALSE, iterations = 3,
  raster = readAll(stack(vrt)), # it seems that brick() is slower than stack()
  terra = set.values(rast(vrt)),
  stars = read_stars(vrt, proxy = FALSE),
  gdalraster = gdalraster_read(vrt),
  rgdal = rgdal_read(vrt)
)
t[, 1:5]
#>   expression      min   median `itr/sec` mem_alloc
#> 1 raster        10.9s   10.94s    0.0910    5.76GB
#> 2 terra         8.11s    8.18s    0.123      3.7KB
#> 3 stars         8.33s    8.34s    0.118     1.82GB
#> 4 gdalraster    9.57s    9.81s    0.102     5.47GB
#> 5 rgdal        13.45s   13.46s    0.0742    4.56GB
```

</details>

**Comment by ctoney** [comment] 2023-05-31 20:38
My tests often use a 30-m elevation raster for the conterminous US provided by LANDFIRE:
https://www.landfire.gov/
The version I'm using here is "LF 2020 [LF 2.2.0]".
The download is 8.41 GB. The raster itself is Int16 6.8 GB GTiff with LZW compression. The download is larger because it also includes overviews. The direct download link is:
https://landfire.gov/bulk/downloadfile.php?FNAME=US_Topo_2020-LF2020_Elev_220_CONUS.zip&TYPE=landfire

Using that, I ran this test to read every pixel in the raster for processing (by row):
```r
library(gdalraster)
library(stars)

# int16 6.8 GB with LZW compression:
f = "LC20_Elev_220.tif" 

ds = new(GDALRaster, f, read_only = TRUE)
ncols = ds$getRasterXSize()
nrows = ds$getRasterYSize()
print(paste("Size is", ncols, "x",  nrows))  # 1.587394e+10 pixels
#> [1] "Size is 156335 x 101538"

set_config_option("GDAL_NUM_THREADS", "4")

gdalraster_read = function(row) {
  r = ds$read(1, 0, row, ncols, 1, ncols, 1)
  ## process pixels, possibly write output...
  return()
}

stars_read = function(row) {
  rasterio = list(nXOff=1, nYOff=row+1, nXSize=ncols, nYSize=1, bands=1)
  r = stars::read_stars(f, options="NUM_THREADS=4", RasterIO=rasterio, proxy=FALSE)[[1]]
  ## process pixels, possibly write output...
  return()
}

system.time( lapply(0:(nrows-1), gdalraster_read) )
#>   user  system elapsed
#> 122.00   62.07  197.09

system.time( lapply(0:(nrows-1), stars_read) )
^C
Timing stopped at: 2.338e+04 3324 8010  # killed with ctrl-C
```

The use of NUM_THREADS is from GDAL documentation for the GTiff driver:
>NUM_THREADS=[<number_of_threads>/ALL_CPUS]: Enable multi-threaded compression by specifying the number of worker threads. Worth it for slow compression algorithms such as DEFLATE or LZMA. Default is compression in the main thread. Starting with GDAL 3.6, this option also enables multi-threaded decoding when RasterIO() requests intersect several tiles/strips. The GDAL_NUM_THREADS configuration option can also be used as an alternative to setting the open option.

It is enable here because we're reading rows across multiple tiles. It speeds up I/O a bit, but the overall result is the same without it. I can explain what I think are reasons for the difference. I can also provide another test that further supports the reasoning. But do you have initial thoughts on the test as constructed?

**Comment by kadyb** [comment] 2023-05-31 22:21
Thanks for this test, the results are very interesting. So we can conclude that loading the raster line by line is very slow in `{stars}`? In this toy example below, I see exactly the same thing:

<details>
<summary>Comparison</summary>

```r
library(stars)
library(gdalraster)

f = system.file("tif/L7_ETMs.tif", package = "stars")
r = read_stars(f, proxy = TRUE)
ncols = dim(r)[1] # 349
nrows = dim(r)[2] # 352

gdalraster_read = function(row) {
  r = ds$read(1, 0, row, ncols, 1, ncols, 1)
  return()
}

stars_read = function(row) {
  rasterio = list(nXOff=1, nYOff=row+1, nXSize=ncols, nYSize=1, bands=1)
  r = stars::read_stars(f, RasterIO=rasterio, proxy=FALSE)[[1]]
  return()
}

ds = new(GDALRaster, f, read_only = TRUE)
system.time({ lapply(0:(nrows-1), gdalraster_read) })
#> user  system elapsed
#> 0.01    0.00    0.01

system.time({ lapply(0:(nrows-1), stars_read) })
#> user  system elapsed
#> 1.61    0.33    1.94

# load whole raster at once
system.time({ read_stars(f, proxy = FALSE) })
#> user  system elapsed
#> 0.01    0.00    0.01
```

</details>

> But do you have initial thoughts on the test as constructed?

I have two thoughts:
1) What if we try to move multithreading from GDAL to R using e.g. `mclapply()` or something like that?
2) `{stars}` supports out-of-the-memory raster processing by default, but this probably works by blocks rather by lines. Maybe we should check this case too?

**Comment by kadyb** [comment] 2023-06-01 11:53
I did one more comparison and the results are quite surprising to me. It seems that the more chunks we want to load in `{stars}`, the more time it takes, while in `{gdalraster}` it is almost constant. Can you confirm this or did I write incorrect code?

![Rplot](https://github.com/USDAForestService/gdalraster/assets/35004826/a689afd8-4afa-4f03-854f-ca467fab54ca)


<details>
<summary>Code</summary>

```r
library("stars")
library("gdalraster")

## https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_39_02.zip
f = "dem/srtm_39_02.tif"
r = read_stars(f, proxy = TRUE)
nrows = nrow(r)
ncols = ncol(r)
block_sizes = c(64, 96, 128, 192, 256, 512, 1024)
timings_stars = double(length(block_sizes))
timings_gdalraster = double(length(block_sizes))

# stars -------------------------------------------------------------------
i = 1
for (size in block_sizes) {
  blocks = st_tile(nrows, ncols, size, size)
  t = system.time({
    for (j in seq_len(nrow(blocks))) {
      read_stars(f, proxy = FALSE, RasterIO = blocks[j, ])
    }
  })
  timings_stars[i] = t[[3]]
  i = i + 1
}

# gdalraster --------------------------------------------------------------
ds = new(GDALRaster, f, read_only = TRUE)

i = 1
for (size in block_sizes) {
  blocks = st_tile(nrows, ncols, size, size)
  blocks[, 1:2] = blocks[, 1:2] - 1L
  t = system.time({
    for (j in seq_len(nrow(blocks))) {
      ds$read(1, blocks[j, 1], blocks[j, 2], blocks[j, 3], blocks[j, 4],
              blocks[j, 3], blocks[j, 4])
    }
  })
  timings_gdalraster[i] = t[[3]]
  i = i + 1
}

ds$close()

# plot --------------------------------------------------------------------
n_block = c(8836, 3969, 2209, 1024, 576, 144, 36)
plot(timings_stars ~ n_block, main = "Data loading performance",
     xlab = "Number of blocks", ylab = "Time [s]", type = "l", col = "red")
lines(timings_gdalraster ~ n_block, col = "blue")
legend("topleft", c("stars", "gdalraster"), col = c("red", "blue"), lty = 1)
```

</details>

**Comment by ctoney** [comment] 2023-06-01 17:08
That is interesting. I think it may be consistent with my results but I need more time to look at your code and see if I can confirm. First I am posting my last test as well. You had wondered about the effect of tiling / reading by block and that is also what I had in mind for an additional test.

A previous version of LANDFIRE elevation ("LF 2014") was available as an Erdas Imagine file that had the block size set to ncols x 1 so that a block is one whole row. I've used that file in testing for a long time and knew that `read_stars()` could read it by row in reasonable time. LF 2014 elevation does not seem to be available on the LANDFIRE website anymore (so reproducible example required the currently available version), but we can create a file like that from the current LANDFIRE elevation file. Keeping it as GTiff:

```r
f2 = "LC20_Elev_220_striped.tif"
options = c("COMPRESS=LZW", "TILED=NO", "BLOCKYSIZE=1", "BIGTIFF=YES")
gdalraster::createCopy("GTiff", f2, f, options=options)
ds2 = new(GDALRaster, f2, TRUE)
```

Now instead of

```r
ds$getBlockSize(band=1)
#> [1] 128 128
```

we have

```r
ds2$getBlockSize(band=1)
#> [1] 156335      1
```

The file size is much larger at 10.6 GB vs. 6.8 GB, since compression is not efficient for strips vs. tiles. But it is now optimized for reading by row. Results are much better for `read_stars()` after substituting `f2` for `f` in the earlier test:

```r

## timings with striped tif

> system.time( lapply(0:(nrows-1), gdalraster_read) )
#>   user  system elapsed
#> 130.00   56.10  186.45

> system.time( lapply(0:(nrows-1), stars_read) )
#>   user  system elapsed
#> 548.46  194.34  776.63
```

I think these results may help in understanding the larger pattern above, but the reasoning is a little involved. It is also interesting that with `{gdalraster}` there is not much penalty when reading rows that intersect many 128 x 128 blocks. I'll add more here once I spend more time thinking through your previous results. Thanks for your engagement on working through this. It's very helpful on my end.

**Comment by ctoney** [comment] 2023-06-02 07:15
Your results are correct but the explanation is lengthy. I will give a brief description here, and add a more detailed version later.

Notice that the SRTM raster is a striped tif, that is, the block size is defined as a strip (one whole row in this case):

```r
f = "srtm_39_02.tif"
ds = new(GDALRaster, f, read_only = TRUE)
ds$getBlockSize(band=1)
#> [1] 6000    1
```

Although tif is a tiled format, it can be arranged in strips instead of square blocks. There is nothing inherently advantageous in reading the SRTM raster in blocks. It is arranged for row-level access. But that is only part of the reason for the results from your test.

GDAL reads blocks (block size of the raster) and uses a block caching mechanism to improve I/O performance. Caching is used for write also, but for reading this amounts to read-ahead caching. That is why I can use `{gdalraster}` to read the tiled LANDFIRE raster efficiently by row. Each row-level read intersects 1222 blocks in that case (block size is 128 x 128). But I don't have to read it by block for good performance thanks to GDAL block caching. Each intersected block is read from disk, decoded from LZW compression, and placed in cache memory. Data for successive reads that intersect the same block are retrieved from cache. That requires using the GDAL API more "natively". With `{gdalraster}` and `{rgdal}` we create a GDAL dataset object, and that object is used repeatedly for read(), write(), etc. The dataset object is only closed when I/O is completely finished. That is how the underlying GDAL API works. (You should be able to substitute `{rgdal}` in any of the above tests and get results very similar to `{gdalraster}`.) `read_stars()` does not create an object in R to hold a GDAL dataset. It is a single function call. So each call to `read_stars()` opens a GDAL dataset, reads one chunk, and then closes the dataset (in the underlying C++ code). But closing empties cache buffers. Doing so after each call to read(), when reading a large raster in successive chunks, has the effect of disabling GDAL block caching. 

I will write a fuller description with detailed explanation of the test results, but it will take more time to put that together. It will also explain more of what it means that `{gdalraster}` is a "low level" interface, with implications for how the I/O scales.

**Comment by edzer** [comment] 2023-06-02 19:25
Thanks for the deep analysis! This seems a good reason for `stars` to keep the `GDALDataset` object open, and glue an external pointer to it onto a `stars_proxy` object, closing only when all processing has been finished or maybe even only when the object gets out of scope.

**Comment by ctoney** [comment] 2023-06-02 21:22
I've not used external pointers but it sounds reasonable.

I do want to be clear that none of the above is meant as a criticism of `{stars}` or to suggest anything is wrong. I've been intending to get to that point in a more detailed write-up. I really like `{stars}`. It does not purport to provide a direct API interface to GDAL. It is a different interface that is very well designed with rich functionality. By comparison, a package like `{gdalraster}` that mainly provides a direct API interface is simpler and more mundane.

The comparisons above evolved from initially looking at benchmark tests based on small rasters that can be loaded in a single call to read(). It is helpful to explore how the I/O scales up. That was the only intent rather than making any specific point about `read_stars()`. The comparisons involve nuance and may not apply generally in many common use cases. I appreciate the engagement here and learn a lot from it.

**Comment by edzer** [comment] 2023-06-04 15:52
Point taken - planning to first look into whether this affects real(istic) work and not only contrived benchmarks before clobbering the current way `stars` works.

**Comment by edzer** [comment] 2023-06-04 19:03
Looking more carefully at @kadyb 's benchmark, `stars` will never do this efficiently, and the fairer comparison would be to open and close `ds` in the same (inner) loop - not saying the benchmark is useless but it's apples and oranges. The idea of `stars` keeping a pointer to a GDALDataset would potentially make sense when a `stars_proxy` object is processed chunk-wise, and then only have an effect (I expect) when the stars chunk size is much smaller than the GDAL read buffer size. That chunk size defaults (now) to some 25 million cells. @ctoney do you know how large the GDAL buffer size is, and whether it can be configured by the user?

**Comment by ctoney** [comment] 2023-06-04 20:39
Default size of the block cache is 40 MB. It can be set by users with the `GDAL_CACHEMAX` config option (`CPLSetConfigOption()`), e.g.,

```r
gdalraster::set_config_option("GDAL_CACHEMAX", "200")
```

It can also be set as an argument to most GDAL command line utilities.

For the example above with LANDFIRE Int16 elevation raster tiled at 128 x 128, one row intersects 1222 blocks (156335 raster columns, partial blocks on the end). So caching them should require 128×128×2 bytes = 32768 bytes per block, 32768 × 1222 = 40042496 bytes, approximately 40 MB which happens to be the default cache size. So all of the decoded block data for a row would fit in cache if I calculated correctly, meaning that only 1 out of every 128 row-level reads would involve retrieval from file and decoding of compressed blocks. The other 127/128 should be provided from cache. (My understanding is that for LZW-compressed tif, compression acts on the individual tiles. Details will vary by raster format, block arrangement and compression method, but similar idea for a few common formats and compression methods).

Row-level processing of large raster files is typical in our applications. I'm working on a short article for `{gdalraster}` to describe the block caching mechanism and setting GDAL_CACHEMAX with that case in mind. User-facing documentation for the block cache is a little thin unless I've missed something. I'll share that once in draft form in case you're interested. Otherwise some of the above comes from:

https://gdal.org/development/rfc/rfc26_blockcache.html
https://gdal.org/user/configoptions.html
https://gdal.org/doxygen/classGDALRasterBlock.html

**Comment by ctoney** [comment] 2023-06-18 17:47
I'm adding a correction above re: default size limit for cache memory.

The source of the 40 MB limit was [RFC 26](https://gdal.org/development/rfc/rfc26_blockcache.html). However from [gcore/gdalrasterblock.cpp](https://github.com/OSGeo/gdal/blob/97f0c0b35c7ca5f17bdd74312bee2a0afa4d2199/gcore/gdalrasterblock.cpp) I see that it was subsequently changed to a default of 5% of usable physical RAM, if `GDAL_CACHEMAX` has not been set at the time when I/O involving the cache first occurs.

I've updated the article with that information and the option of setting `GDAL_CACHEMAX` as MB or % of physical RAM.

Also added `gdalraster::get_cache_used()` in [main](https://github.com/USDAForestService/gdalraster). Enables checking the amount of RAM in use for the block cache. Added that in the article to further confirm the description of cache operation.

[GDAL block caching](https://usdaforestservice.github.io/gdalraster/articles/gdal-block-cache.html)

**Closed** 2024-03-05 10:51 UTC
